### ISSUE TITLE
Egyéb típusú címkék predikciója (M1)

### ISSUE THREAD

**Issue by pisipite** [k-monitor/sajtoadatbazis-automat#200]
_Cél_: egy-az-egyben megfeleltetés kiválasztott [címkéknél](https://docs.google.com/spreadsheets/d/1gfTFSvSsIe0l2rz6odjDQheYaBhwBb72i33Wft9eC9s/edit?gid=960560330#gid=960560330). 
_Megoldás_: beolvasott cikkszövegen és címkeválasztóban a többihez hasonlóan mutassa ezeket is. Megfeleltethetőség db-ben tárolódjon.

**Comment by boapps** [comment]
TODO: Javítani lassú betöltést és a db-ben tárolni a szinonímákat.

**Comment by pisipite** [comment]
most működni látszik.
viszont a megjelenítésére korábban azt beszéltük, hogy a cikkszövegben ne új színnel (félkövérrel) kiemelve jelenjenek ezek meg, hanem a háttérszíne térjen el a szövegkörnyezettől.
valami ilyesmi módon:
![kép](https://github.com/user-attachments/assets/40db2525-0abc-4c4d-b526-296990872d17)

**Comment by boapps** [comment]
Áh, igazad van, bocsi.
