### ISSUE TITLE
egy cikk kétszer elfogadásának tiltása

### ISSUE THREAD

**Issue by pisipite** [k-monitor/sajtoadatbazis-automat#214]
az olyan véletlen helyzetek elleni védelem érdekében, amikor egyszerre nyit meg két felhasználó egy cikket. ilyenkor a csak az előbbi elfogadás legyen érvényes, a későbbi ne írja felül azt (adjon hibaüzenetet).

**Comment by pisipite** [comment]
az a tippem, hogy ezzel a körrel a már egyszer elutasított cikkeknél a 'mégis elfogad' funkció elromlott. legalábbis ezt mondja: 'Szerkesztés közben megváltozott a cikk státusza. Kérlek töltsd újra az oldalt!'

**Comment by boapps** [comment]
köszi! ha minden igaz, javítottam.
