### ISSUE TITLE
vizualitás

### ISSUE THREAD

**Issue by pisipite** [k-monitor/sajtoadatbazis-automat#221]
Ferencz Miki készített egy vizuális ráncfelvarrás [tervet](https://www.figma.com/design/Wh2JEHvK9g5VBSNSht4TCk/audit?node-id=44-2&t=3MQ5aqmcdhkjilih-0). ennek elemei:

- [x] vizuális hierarchia a címekben
- [ ] szövegdobozok körvonalainak megerősítése
- [x] vezérlőgombok egy vonalban szövegdobozokkal
- [x] aktív gomb toggle-sítése

- elutasítás: #220

**Comment by boapps** [comment]
Illetve itt egy before-after összehasonlítás a UI módosításokról.

Before:
![Screenshot 2024-08-06 at 17-23-07 ](https://github.com/user-attachments/assets/c045aea0-3851-494a-ae65-588cea2299fc)

After:
![Screenshot 2024-08-06 at 17-23-21 ](https://github.com/user-attachments/assets/c9a0a07a-9c96-4b3a-adc7-148f8005dbe8)

Szólj ha valamit másképp gondoltál!

**Comment by pisipite** [comment]
vagány!
körvonalaknál azt értettem, amit Miki ajánlott a [figmában](https://www.figma.com/design/Wh2JEHvK9g5VBSNSht4TCk/audit?node-id=44-2&t=5tUUOa92RW8TJhVx-0). de igazából jó így, ahogy csináltad!
