### ISSUE TITLE
javított cikk nem látszik az elfogadott dobozban

### ISSUE THREAD

**Issue by pisipite** [k-monitor/sajtoadatbazis-automat#223]
van egy [atlatszo.hu-s cikk](https://atlatszo.hu/kozpenz/2024/08/28/tobb-sebbol-verzik-a-82-milliardos-tender-de-a-gvh-nem-indit-versenyfelugyeleti-eljarast), amit nem illendőnek kategorizált. felülbíráltam és elfogadtam, be is került az adatbázisba. viszont az autokmdb-n az elfogadottak listájába nem került be (a mindegyikben ott van és ott van előtte is a zöld doboz).

**Comment by boapps** [comment]
Javítva
