### ISSUE TITLE
pontozott felsorolást nem látja a szövegben

### ISSUE THREAD

**Issue by pisipite** [k-monitor/sajtoadatbazis-automat#225]
sem a szöveget nem szívja be, sem az entitásokat nem ismeri fel a pontozott felsorolásból.

- https://telex.hu/belfold/2024/08/28/simonka-gyorgy-interju-fidesz-pusztaottlaka-lazar-janos-rogan-antal-orban-viktor-koltsegvetesi-csalas
- https://telex.hu/belfold/2024/08/28/simonka-gyorgy-kozponti-nyomozo-fougyeszseg-reakcio
- https://telex.hu/belfold/2024/08/23/horvath-csaba-toth-csaba-molnar-zsolt-baja-ferenc-korrupcio-szamlagyar-f-zsolt-vademeles-ugyeszseg

**Comment by boapps** [comment]
A hiba a Telex-hez külön készített szövegkinyerő logikában volt. Javítva.
