### ISSUE TITLE
entitások listájában kapcsolódó cikkek számának megjelenítése

### ISSUE THREAD

**Issue by pisipite** [k-monitor/sajtoadatbazis-automat#232]
felajánlott entitások listájában (legördülő menü) hasznos infó lenne megjeleníteni az adott entitáshoz kapcsolódó cikkek számát (zárójelben).

**Comment by boapps** [comment]
#273-ban bekerült

**Comment by pisipite** [comment]
szuper lett!
a kiválasztást mutató pipával összecsúszik, ezt még jó, ha javítod:
![kép](https://github.com/user-attachments/assets/55715564-feb2-4eee-9c00-ecb7c49f66ad)

**Comment by boapps** [comment]
Ouch, ezt nem vettem észre.
Egyelőre arrébb tettem a számot, amíg ki nem találunk valami szebb megoldást.
![image](https://github.com/user-attachments/assets/eccf0942-d679-41ba-9750-f1a7678b7038)

**Comment by pisipite** [comment]
tök jó így, köszi!

**Comment by pisipite** [comment]
egyéb címkéknél nem működik:
![kép](https://github.com/user-attachments/assets/426105ad-7589-4ba0-93b9-5a65098199fc)

**Comment by boapps** [comment]
Javítva: #283
