### ISSUE TITLE
már elfogadott cikk szerkesztése és mentése

### ISSUE THREAD

**Issue by pisipite** [k-monitor/sajtoadatbazis-automat#233]
már elfogadott (adatbázisban szereplő) cikk szerkesztése esetén nem működik a mentés (_elfogadás_), ezt mondja:
`Ez a cikk url alapján már szerepel az adatbázisban. Valószínűleg az autokmdb-n kívülről lett hozzáadva.`
már elfogadott cikkek esetében ne `Elfogad` gomb legyen a zöld, hanem `Módosítások mentése`.

**Comment by boapps** [comment]
Ha minden igaz #241 javította a hibát.
