### ISSUE TITLE
cikkszöveg beolvasás Telex-nél a felsorolást lehagyja

### ISSUE THREAD

**Issue by pisipite** [k-monitor/sajtoadatbazis-automat#239]
[ebben a telex](https://telex.hu/gazdasag/2024/09/04/forbes-legertekesebb-csaladi-cegek-meszaros-csoport) cikkben pl. a számozott felsorolás elemeit nem olvasta be.

**Comment by boapps** [comment]
Ezt a hibát egyszer már javítottam (#225 és #228), pont szeptember 4.-én és ez is egy szeptember 4. délelőtti cikk.
[Ebben](https://telex.hu/gazdasag/2024/09/12/transparency-international-tanulmany-magantokealapok-szabalyozas) a cikkben már behúzza a felsorolást is.
