### ISSUE TITLE
szövegekben a linkek körül eltűnik a space

### ISSUE THREAD

**Issue by pisipite** [k-monitor/sajtoadatbazis-automat#252]
mostanában szembe jött több olyan is, amikor kimarad a felismert entitások körül egy-egy szóköz. elkezdem gyűjteni.
![kép](https://github.com/user-attachments/assets/0bea9d08-0297-4d97-8d7e-f286a3542983)
https://www.delmagyar.hu/helyi-kek-hirek/2024/10/putnik-lazar-birosag-buntetoper

**Comment by pisipite** [comment]
magyarnemzetnél is:
https://magyarnemzet.hu/belfold/2024/10/december-vegeig-bortonben-maradhat-czegledy-gergo-obuda-alpolgarmestere
![kép](https://github.com/user-attachments/assets/ad31be3c-8e50-4c42-afdd-2062608ab8b7)

**Comment by boapps** [comment]
A probléma mediaworks-ös cikkeknél volt, az új saját parser-ben.

**Comment by boapps** [comment]
#253 javítja
