### ISSUE TITLE
elfogadás után köszi üzenet

### ISSUE THREAD

**Issue by pisipite** [k-monitor/sajtoadatbazis-automat#254]
szuper lenne megköszönni a cikkbevivőnek a munkáját miután elfogadott egy cikket. egy pár másodpercig látható üzenetre gondoltam, ami kb. addig jelenik meg, míg tölt az elfogadás után és magától (kattintás nélkül) eltűnik. ez lehetne:
`Köszi, hogy ezzel a cikkel is bővítetted a K-Monitor sajtóadatbázisát!`
ennek egy továbbfejlesztett verziója, hogy véletlenszerűen egy listából ad ki egyet. szívesen írok nekik kedves üzeneteket.

**Comment by boapps** [comment]
#273 -ban bekerült ez is, szuper ha írsz listát

**Comment by pisipite** [comment]
oks! szuper vagy, írok hamarosan!

**Comment by pisipite** [comment]
Egyelőre ennyi, még majd írok párat. Olyat tudsz, hogy minden második megjelenés legyen az első (mostani) szöveg a többi pedig véletlenszerűen a lista többi eleme közül valamelyik?

- Köszi, hogy ezzel a cikkel is bővítetted a K-Monitor sajtóadatbázisát!
- Köszi a beküldést, köszi a munkát!
- Ennek a cikknek az elfogadásával Magyarország legnagyobb közpénzes, korrupciós adatbázisát bővítetted! Köszi!
- Együtt építjük a sajtóadatbázist. Köszi!
- A K-Monitor sajtóadatbázisa 2007 óta gyűjti a közpénzes, korrupciós cikkeket. Köszi, hogy része vagy!

**Comment by boapps** [comment]
Azt kicsit bonyolultabb lenne megoldani, hogy pont minden második üzenet az legyen, ami a listában az első. De olyat nagyon egyszerűen tudok csinálni, hogy mindegyik random, de az első üzenet valószínűsége nagyobb (pl 50%).

**Comment by pisipite** [comment]
szuper!

**Comment by boapps** [comment]
Még #290-ben bekerült.
