### ISSUE TITLE
szűrés url nem mindig működik

### ISSUE THREAD

**Issue by pisipite** [k-monitor/sajtoadatbazis-automat#279]
kiválasztott hírportálokkal módosított url-re előfordul, hogy nem a szelekció tölt be, hanem szűrés nélkül a teljes feed. egyelőre nem sikerült rájönnöm, hogy mikor nem működik (kb. fele-fele arányban).

**Comment by boapps** [comment]
Azt hiszem refactorolás közben a frontend komponensek átrendezése ronthatta el.
Szerintem igazából már a szelekció url-be írása se megy jól.
Megoldás: a szelekció módosítása után mindenképp lefuttatjuk az url-be írást.
Köze lehet a #275-hez.

**Comment by boapps** [comment]
Javítva: #285
