### ISSUE TITLE
444 cikkek hibás beolvasása

### ISSUE THREAD

**Issue by pisipite** [k-monitor/sajtoadatbazis-automat#281]
nem húzza be az adatokat a 444.hu-ról érkező cikkekhez: 
![kép](https://github.com/user-attachments/assets/b96aca79-face-4dd0-9537-ac00f88d31d5)

**Comment by boapps** [comment]
Nem mindig ment üresen cikkeket, ami arra utal, hogy (valószínűleg külföldi ip miatt) egy captchas oldalt dobhat fel a botok elleni védekezés miatt vagy valami más okból néha nem jelenik meg az oldalon a cikk.
Az viszont mindenképp probléma, hogy nem hibásan feldolgozottként menti el, mert akkor újra tudna próbálkozni. Most átírom a logikát, hogy ha üres cím van, akkor azt vegye hibának.

**Comment by boapps** [comment]
A korábban üres címmel felvett cikkeket is hozzáadtam a feldolgozási sorhoz és kicsit javítottam még a hibák felismerésén.
