### ISSUE TITLE
greenfo cikkek hibás beolvasása

### ISSUE THREAD

**Issue by pisipite** [k-monitor/sajtoadatbazis-automat#300]
![kép](https://github.com/user-attachments/assets/a7a3f28e-75db-42fd-a770-f2e623888969)

**Comment by boapps** [comment]
Úgy látszik a Greenfo-nál vannak sima cikkek és sajtófigyelős cikkek (amik nem is külön cikkek, csak egy listába gyűjtik őket). A sima cikkeket jól beolvassa a rendszer. A sajtófigyelős cikkek viszont átirányítanak [ide](https://greenfo.hu/sajtofigyelo/), a listára.
Szerintem sajtófigyelős cikkek nem kellenek.
Megoldás terv: ki kell hagyni azokat a cikkeket amik url-je ezzel kezdődik: `https://greenfo.hu/sajtofigyelo/`.

**Comment by pisipite** [comment]
kösz! beírtam a [táblába](https://docs.google.com/spreadsheets/d/1gfTFSvSsIe0l2rz6odjDQheYaBhwBb72i33Wft9eC9s/edit?gid=754964742#gid=754964742).

**Comment by boapps** [comment]
Javítva: #303
